# https://en.wikipedia.org/wiki/List_of_African_cuisines#Central_African_cuisine
# https://en.wikipedia.org/wiki/African_cuisine#Central_Africa

[translation]
  [translation.en]
    term = "central africa"
    adj = "central african"
