# https://en.wikipedia.org/wiki/List_of_African_cuisines#Horn_African_cuisine
# https://en.wikipedia.org/wiki/African_cuisine#Horn_of_Africa

type = "subregion"

[translation]
  [translation.en]
    term = "horn africa"
    adj = "horn african"
  [translation.es]
   term = "cuerno de Ã¡frica"
   adj = "cuerno africano"
