# https://en.wikipedia.org/wiki/List_of_African_cuisines#Southern_African_cuisine
# https://en.wikipedia.org/wiki/African_cuisine#Southern_Africa

type = "subregion"

[translation]
  [translation.en]
    term = "southern africa"
    adj = "southern african"
