# https://en.wikipedia.org/wiki/Cuisine#Asian_cuisine
# https://en.wikipedia.org/wiki/List_of_Asian_cuisines

type = "continent"

[translation]
  [translation.en]
    term = "asia"
    adj = "asian"
  [translation.es]
    term = "asia"
    adj = "asi√°tica"
