# https://en.wikipedia.org/wiki/Cuisine#European_cuisine
# https://en.wikipedia.org/wiki/List_of_European_cuisines

type = "continent"

[translation]
  [translation.en]
    term = "europe"
    adj = "european"
  [translation.es]
    term = "europa"
    adj = "europea"
