# https://en.wikipedia.org/wiki/Herb (Culinary Herb) : Possibly belongs under vegetables?
exclude-diet = ["carnivorous"]

[translation]
  [translation.en]
    term = "herb"
  [translation.es]
    term = "hierbas"
